// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/api/gamelist/service.proto

package gamelist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameListRequest) Reset()         { *m = GameListRequest{} }
func (m *GameListRequest) String() string { return proto.CompactTextString(m) }
func (*GameListRequest) ProtoMessage()    {}
func (*GameListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8b9aa6375ce9f5, []int{0}
}

func (m *GameListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameListRequest.Unmarshal(m, b)
}
func (m *GameListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameListRequest.Marshal(b, m, deterministic)
}
func (m *GameListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameListRequest.Merge(m, src)
}
func (m *GameListRequest) XXX_Size() int {
	return xxx_messageInfo_GameListRequest.Size(m)
}
func (m *GameListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameListRequest proto.InternalMessageInfo

type GameListResponse struct {
	Games                []string `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameListResponse) Reset()         { *m = GameListResponse{} }
func (m *GameListResponse) String() string { return proto.CompactTextString(m) }
func (*GameListResponse) ProtoMessage()    {}
func (*GameListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd8b9aa6375ce9f5, []int{1}
}

func (m *GameListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameListResponse.Unmarshal(m, b)
}
func (m *GameListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameListResponse.Marshal(b, m, deterministic)
}
func (m *GameListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameListResponse.Merge(m, src)
}
func (m *GameListResponse) XXX_Size() int {
	return xxx_messageInfo_GameListResponse.Size(m)
}
func (m *GameListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameListResponse proto.InternalMessageInfo

func (m *GameListResponse) GetGames() []string {
	if m != nil {
		return m.Games
	}
	return nil
}

func init() {
	proto.RegisterType((*GameListRequest)(nil), "gamelists.GameListRequest")
	proto.RegisterType((*GameListResponse)(nil), "gamelists.GameListResponse")
}

func init() {
	proto.RegisterFile("rpc/api/gamelist/service.proto", fileDescriptor_cd8b9aa6375ce9f5)
}

var fileDescriptor_cd8b9aa6375ce9f5 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x2a, 0x48, 0xd6,
	0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0x4f, 0xcc, 0x4d, 0xcd, 0xc9, 0x2c, 0x2e, 0xd1, 0x2f, 0x4e, 0x2d,
	0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x89, 0x17, 0x2b,
	0x09, 0x72, 0xf1, 0xbb, 0x27, 0xe6, 0xa6, 0xfa, 0x64, 0x16, 0x97, 0x04, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x28, 0x69, 0x70, 0x09, 0x20, 0x84, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44,
	0xb8, 0x58, 0x41, 0x7a, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x20, 0x1c, 0xa3, 0x30,
	0x2e, 0x1e, 0xf7, 0xd4, 0x12, 0x98, 0xe2, 0x62, 0x21, 0x37, 0x2e, 0x6e, 0x24, 0xbe, 0x90, 0x94,
	0x1e, 0xdc, 0x1e, 0x3d, 0x34, 0x4b, 0xa4, 0xa4, 0xb1, 0xca, 0x41, 0x6c, 0x73, 0xe2, 0x8a, 0xe2,
	0x80, 0xc9, 0x26, 0xb1, 0x81, 0x9d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xf0, 0x8c,
	0x8e, 0xd4, 0x00, 0x00, 0x00,
}
